### ISSUE TITLE
能否设置pr提交，这样就可以进行版本管理了

### ISSUE THREAD

**Issue by yatingzhou** [hlcfans/hlcfans.github.io#1]
https://github.com/hlcfans/hlcfans.github.io/commit/74b0c28d805938316af873b56e5d1a8ff349f365

建议设置pull request权限，大家的修改需要先进行pr，然后你和我review过后再进行merge。

**Comment by yatingzhou** [comment]
@kittencup

**Comment by lawrencedxb** [comment]
how to paly?

**Comment by kittencup** [comment]
我没有权限

**Comment by blocklee** [comment]
现在这个账号的权限在谁那里啊，我的想法是把 hlcfans 设置成一个组织（Organization）这样方便做一些权限管理，我看这个 hlcfans 是一个个人账号模式，不是很方便拉入更多人来做贡献

**Comment by blocklee** [comment]
如果把 hlcfans弄成一个组织，那么可以在下面建立更多的分类库，还可以方便用 GitHub page 展示
